# Generated by Django 5.1.11 on 2025-07-15 17:57

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_recalculate_durations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the medication administered",
                        max_length=255,
                        verbose_name="Medicine Name",
                    ),
                ),
                (
                    "dosage",
                    models.FloatField(
                        help_text="Amount of medication given", verbose_name="Dosage"
                    ),
                ),
                (
                    "dosage_unit",
                    models.CharField(
                        choices=[
                            ("mg", "MG"),
                            ("ml", "ML"),
                            ("tablets", "Tablets"),
                            ("drops", "Drops"),
                            ("tsp", "Teaspoons"),
                            ("tbsp", "Tablespoons"),
                        ],
                        max_length=20,
                        verbose_name="Dosage Unit",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.localtime,
                        verbose_name="Time",
                    ),
                ),
                (
                    "next_dose_interval",
                    models.DurationField(
                        blank=True,
                        help_text="Time until next dose can be given",
                        null=True,
                        verbose_name="Next Dose Interval",
                    ),
                ),
                (
                    "next_dose_time",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Calculated time when next dose is allowed",
                        null=True,
                        verbose_name="Next Dose Time",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this medication is given on a schedule (vs as-needed for relief)",
                        verbose_name="Recurring Medication",
                    ),
                ),
                (
                    "last_given_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this medication was last administered",
                        null=True,
                        verbose_name="Last Given Time",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this medication is still being tracked",
                        verbose_name="Active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "tags",
                    core.models.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="core.Tagged",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine",
                "verbose_name_plural": "Medicines",
                "ordering": ["-time"],
                "default_permissions": ("view", "add", "change", "delete"),
                "indexes": [
                    models.Index(
                        fields=["child", "-time"], name="medicine_child_time_idx"
                    ),
                    models.Index(
                        fields=["next_dose_time"], name="medicine_next_dose_time_idx"
                    ),
                    models.Index(
                        fields=["child", "name", "time"],
                        name="medicine_duplicate_check_idx",
                    ),
                    models.Index(
                        fields=["is_active", "child", "-last_given_time"],
                        name="medicine_active_status_idx",
                    ),
                    models.Index(
                        fields=["last_given_time"], name="medicine_last_given_idx"
                    ),
                ],
            },
        ),
    ]
