# Generated by Django 5.1.11 on 2026-04-18 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_medicine"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bmi",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "BMI",
                "verbose_name_plural": "BMI",
            },
        ),
        migrations.AlterModelOptions(
            name="headcircumference",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Head Circumference",
                "verbose_name_plural": "Head Circumference",
            },
        ),
        migrations.AlterModelOptions(
            name="height",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Height",
                "verbose_name_plural": "Height",
            },
        ),
        migrations.AlterModelOptions(
            name="weight",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Weight",
                "verbose_name_plural": "Weight",
            },
        ),
        migrations.AddField(
            model_name="medicine",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this medication is still being tracked",
                verbose_name="Active",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="is_recurring",
            field=models.BooleanField(
                default=False,
                help_text="Check if this medication is given on a schedule (vs as-needed)",
                verbose_name="Recurring Medication",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="last_given_time",
            field=models.DateTimeField(
                blank=True,
                help_text="When this medication was last administered",
                null=True,
                verbose_name="Last Given Time",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="next_dose_time",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Calculated time when next dose is allowed",
                null=True,
                verbose_name="Next Dose Time",
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="time",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.localtime,
                verbose_name="Time Taken",
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["child", "-time"], name="medicine_child_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["next_dose_time"], name="medicine_next_dose_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["is_active", "child", "-last_given_time"],
                name="medicine_active_idx",
            ),
        ),
    ]
