# Generated by Django 5.1.11 on 2025-07-13 20:07

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_medicine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="tags",
            field=core.models.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="core.Tagged",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
