# Generated by Django 5.1.11 on 2025-07-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_medicine_tags"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["child", "-time"], name="medicine_child_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["next_dose_time"], name="medicine_next_dose_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["child", "medicine_name", "time"],
                name="medicine_duplicate_check_idx",
            ),
        ),
    ]
