# Generated by Django 5.1.11 on 2025-07-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_add_medicine_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this medication is still being tracked",
                verbose_name="Active",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="is_recurring",
            field=models.BooleanField(
                default=False,
                help_text="Check if this medication is given on a schedule (vs as-needed for relief)",
                verbose_name="Recurring Medication",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="last_given_time",
            field=models.DateTimeField(
                blank=True,
                help_text="When this medication was last administered",
                null=True,
                verbose_name="Last Given Time",
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["is_active", "child", "-last_given_time"],
                name="medicine_active_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["last_given_time"], name="medicine_last_given_idx"
            ),
        ),
    ]
