# Generated by Django 5.1.11 on 2025-07-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_add_medicine_safety_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicine",
            old_name="medicine_name",
            new_name="name",
        ),
    ]
