# Generated by Django 5.1.11 on 2025-07-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_rename_medicine_name_to_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="medicine",
            name="medicine_duplicate_check_idx",
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["child", "name", "time"], name="medicine_duplicate_check_idx"
            ),
        ),
    ]
